Algoritmo "Total compra"

Var
// Seção de Declarações das variáveis 
preco: real
totalComprado: inteiro
valorFinal: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Total de produtos comprados: ")
leia(totalComprado)

escreva("Valor do produto: ")
leia(preco)

valorFinal <- totalComprado * preco

escreva("Valor da compra: ", valorFinal)

Fimalgoritmo
