Algoritmo "Soma de dois valores"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
primeiro: inteiro
segundo: inteiro
resultado: inteiro

Inicio

escreva("Digite o primeiro valor:")
leia(primeiro) // primeiro <- 15

escreva("Digite o segundo valor")
leia(segundo)

resultado <- primeiro + segundo

escreval("O resultado da soma é: ", resultado, " da soma")


Fimalgoritmo
