Algoritmo "Natação"

Var
   idade: inteiro
   nome: caractere

Inicio

   // Entrada
   escreva("Qual a sua idade? ")
   leia(idade)

   // Processamento
   se idade < 15 entao
      // Só entrará se a idade for menor que 15
      // Saida
      escreval("AlUnO AcEiTo")

      escreva("Digite seu nome: ")
      leia(nome)

      escreva("Nome do aluno: ", nome)

      // Processamento
   senao
      // Saida
      escreval("Aluno nao aceito")
   fimse


Fimalgoritmo